name: cvmhsbcbn-ci

on:
  push:
    branches: [ main ]

#on:
#  push:
#    paths:
#      - 'trigger-runner'

jobs:
  cvmhsbcbn-build-standalone-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/cvmhbn/target" >> $GITHUB_ENV
    - name: checkout cvmhbn main
      uses: actions/checkout@v2
      with: 
        ref: main
    - name: generate cvmhsbcbn 
      run: ./.github/scripts/cvmhbn-generate.sh cvmhsbcbn 
      shell: bash
    - name: build cvmhsbcbn 
      run: ./.github/scripts/cvmhbn-build.sh cvmhsbcbn 
      shell: bash
    - name: test cvmhsbcbn standalone
      run: ./.github/scripts/cvmhbn-test-standalone.sh cvmhsbcbn
      shell: bash
#    - name: Start SSH via Ngrok
#      if: ${{ success() }}
#      uses: luchihoratiu/debug-via-ssh@main
#      with:
#            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
#            NGROK_TIMEOUT: 3000
#            SSH_PASS: ${{ secrets.NGROK_SECRET }}

  cvmhsbcbn-build-standalone-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/cvmhbn/target" >> $GITHUB_ENV
    - name: checkout cvmhbn main
      uses: actions/checkout@v2
      with: 
        ref: main
    - name: generate cvmhsbcbn 
      run: ./.github/scripts/cvmhbn-generate.sh cvmhsbcbn 
      shell: bash
    - name: build cvmhsbcbn
      run: ./.github/scripts/cvmhbn-build.sh cvmhsbcbn
      shell: bash
    - name: Start SSH via Ngrok
      if: ${{ failure() }}
      uses: luchihoratiu/debug-via-ssh@main
      with:
            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
            NGROK_TIMEOUT: 3000
            SSH_PASS: ${{ secrets.NGROK_SECRET }}
    - name: test cvmhsbcbn standalone
      run: ./.github/scripts/cvmhbn-test-standalone.sh cvmhsbcbn
      shell: bash
