name: cvmhvbn-ci

#on:
#  repository_dispatch:
#    types: [trigger-cvmhvbn-ci]

on:
   workflow_run:
      workflows: [cvmhbn-ci]
      types:
        - completed

jobs:
  cvmhvbn-build-standalone-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/cvmhbn/target" >> $GITHUB_ENV
    - name: checkout cvmhbn main
      uses: actions/checkout@v2
      with: 
        ref: main
    - name: generate cvmhvbn 
      run: ./.github/scripts/cvmhbn-generate.sh cvmhvbn 
      shell: bash
    - name: build cvmhvbn 
      run: ./.github/scripts/cvmhbn-build.sh cvmhvbn 
      shell: bash
    - name: test cvmhvbn standalone
      run: ./.github/scripts/cvmhbn-test-standalone.sh cvmhvbn
      shell: bash
#    - name: Start SSH via Ngrok
#      if: ${{ success() }}
#      uses: luchihoratiu/debug-via-ssh@main
#      with:
#            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
#            NGROK_TIMEOUT: 3000
#            SSH_PASS: ${{ secrets.NGROK_SECRET }}

  cvmhvbn-build-standalone-linux:
    if: ${{ always() }}
    needs: [cvmhvbn-build-standalone-mac]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/cvmhbn/target" >> $GITHUB_ENV
    - name: checkout cvmhbn main
      uses: actions/checkout@v2
      with: 
        ref: main
    - name: generate cvmhvbn 
      run: ./.github/scripts/cvmhbn-generate.sh cvmhvbn 
      shell: bash
    - name: Start SSH via Ngrok
      if: ${{ success() }}
      uses: luchihoratiu/debug-via-ssh@main
      with:
            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
            NGROK_TIMEOUT: 3000
            SSH_PASS: ${{ secrets.NGROK_SECRET }}
    - name: build cvmhvbn
      run: ./.github/scripts/cvmhbn-build.sh cvmhvbn
      shell: bash
    - name: Start SSH via Ngrok
      if: ${{ failure() }}
      uses: luchihoratiu/debug-via-ssh@main
      with:
            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
            NGROK_TIMEOUT: 3000
            SSH_PASS: ${{ secrets.NGROK_SECRET }}
    - name: test cvmhvbn standalone
      run: ./.github/scripts/cvmhbn-test-standalone.sh cvmhvbn
      shell: bash
